"use client";

import { useEffect, useState } from "react";
import { ConfusionTable, HorizontalBars, PerformanceLines } from "@/components/charts";
import { Card, ErrorPanel, PageHeading, SkeletonGrid } from "@/components/ui";
import { getFeatureImportance, getModelPerformance, getRobustness, records } from "@/lib/api";

export default function ModelInsightsPage() {
  const [performance, setPerformance] = useState<Record<string, unknown> | null>(null); const [importance, setImportance] = useState<Record<string, unknown> | null>(null); const [robustness, setRobustness] = useState<Record<string, unknown> | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  async function load() { setLoading(true); setError(""); const results = await Promise.allSettled([getModelPerformance(), getFeatureImportance(), getRobustness()]); if (results[0].status === "fulfilled") setPerformance(results[0].value); if (results[1].status === "fulfilled") setImportance(results[1].value); if (results[2].status === "fulfilled") setRobustness(results[2].value); const failed = results.find((result) => result.status === "rejected"); if (failed?.status === "rejected") setError(failed.reason instanceof Error ? failed.reason.message : "Model insights are unavailable."); setLoading(false); }
  useEffect(() => { Promise.allSettled([getModelPerformance(), getFeatureImportance(), getRobustness()]).then((results) => { if (results[0].status === "fulfilled") setPerformance(results[0].value); if (results[1].status === "fulfilled") setImportance(results[1].value); if (results[2].status === "fulfilled") setRobustness(results[2].value); const failed = results.find((result) => result.status === "rejected"); if (failed?.status === "rejected") setError(failed.reason instanceof Error ? failed.reason.message : "Model insights are unavailable."); setLoading(false); }); }, []);
  if (loading) return <><PageHeading eyebrow="Model evaluation" title="Model Insights" description="Review the final model alongside its recorded evaluation and robustness evidence." /><SkeletonGrid /></>;
  if (error && !performance) return <><PageHeading eyebrow="Model evaluation" title="Model Insights" description="Review the final model alongside its recorded evaluation and robustness evidence." /><ErrorPanel message={error} retry={() => void load()} /></>;
  const metrics = (performance?.final_metrics as Record<string, unknown> | undefined)?.cv_and_historical_holdout as Record<string, number | string>[] | undefined ?? [];
  const holdout = metrics.find((row) => row.metric === "macro_f1");
  const classRows = records(performance?.final_class_metrics);
  const rawImportance = records(importance?.raw_feature_importance).slice(0, 10).map((row) => ({ ...row, label: String(row.raw_feature).replaceAll("_", " "), value: Number(row.mean_importance) }));
  const countryRows = records(robustness?.country_robustness).map((row) => ({ ...row, score: Number(row.macro_f1_observed_classes) })).sort((a,b) => Number(b.score)-Number(a.score));
  const curveRows = records(robustness?.learning_curves).filter((row) => row.configuration === "Locked RF");
  return <div className="page-enter"><PageHeading eyebrow="Model evaluation" title="Model Insights" description="The Random Forest production pipeline, its recorded validation results, and cross-country diagnostics." />
    <div className="model-overview"><div><span className="eyebrow">Final model</span><h2>Random Forest</h2><p>Tree base preprocessing · 60 selected processed features · no imbalance resampling</p></div><div className="headline-score"><strong>{Number(holdout?.holdout ?? 0).toFixed(4)}</strong><span>Historical holdout Macro-F1</span></div><div className="headline-score secondary-score"><strong>{Number(holdout?.repeated_cv ?? 0).toFixed(4)}</strong><span>Repeated CV Macro-F1</span></div></div>
    <div className="dashboard-grid"><div className="grid-6"><Card title="Recorded final metrics" subtitle="Repeated cross-validation and previously recorded holdout"><div className="table-wrap"><table className="data-table"><thead><tr><th>Metric</th><th>Repeated CV</th><th>Historical holdout</th></tr></thead><tbody>{metrics.filter((row) => ["macro_f1","mcc","accuracy","balanced_accuracy","partial_recall","partial_f1"].includes(String(row.metric))).map((row) => <tr key={String(row.metric)}><th>{String(row.metric).replaceAll("_", " ")}</th><td>{Number(row.repeated_cv).toFixed(3)}</td><td>{Number(row.holdout).toFixed(3)}</td></tr>)}</tbody></table></div><p className="metric-note">Holdout results are historical records and were not recomputed for this dashboard.</p></Card></div>
      <div className="grid-6"><Card title="Class-level holdout results" subtitle="Per-class precision, recall, F1, and support"><div className="table-wrap"><table className="data-table"><thead><tr><th>Class</th><th>Precision</th><th>Recall</th><th>F1</th><th>Support</th></tr></thead><tbody>{classRows.map((row) => <tr key={String(row.class)}><th>{String(row.class)}</th><td>{Number(row.precision).toFixed(2)}</td><td>{Number(row.recall).toFixed(2)}</td><td>{Number(row.f1).toFixed(2)}</td><td>{row.support}</td></tr>)}</tbody></table></div></Card></div>
      <div className="grid-12"><Card title="Baseline and optimized candidates" subtitle="Repeated cross-validation · Macro-F1"><div className="table-wrap"><table className="data-table"><thead><tr><th>Model family</th><th>Baseline Macro-F1</th><th>Optimized Macro-F1</th><th>Change</th><th>Partial-class recall</th></tr></thead><tbody>{records(performance?.baseline_vs_optimized).map((row) => <tr key={String(row.family)}><th>{String(row.family)}</th><td>{Number(row.baseline_macro_f1).toFixed(3)}</td><td>{Number(row.optimized_macro_f1).toFixed(3)}</td><td>{Number(row.macro_f1_change) >= 0 ? "+" : ""}{Number(row.macro_f1_change).toFixed(3)}</td><td>{Number(row.optimized_partial_recall).toFixed(3)}</td></tr>)}</tbody></table></div></Card></div>
      <div className="grid-12"><ConfusionTable rows={records(performance?.final_confusion_matrix)} /></div>
      <div className="grid-6"><HorizontalBars title="Raw feature importance" subtitle="Mean permutation importance" rows={rawImportance} nameKey="label" valueKey="value" color="#4D728F" footer={<p className="metric-note">Importance reflects predictive reliance, not causation.</p>} /></div>
      <div className="grid-6"><HorizontalBars title="Cross-country robustness" subtitle="Leave-one-country-out Macro-F1 · observed classes" rows={countryRows} nameKey="country" valueKey="score" color="#25AFC0" /></div>
      <div className="grid-12"><PerformanceLines rows={curveRows} /></div>
      <div className="grid-12"><Card title="Reading these results" subtitle="Evaluation notes"><div className="insight-grid"><p><b>CV and holdout:</b> Repeated CV summarizes development folds. Historical holdout metrics come from the project&apos;s recorded final evaluation and are not mixed with CV.</p><p><b>Country robustness:</b> Leave-one-country-out results measure transfer across country groups; they are not a standard stratified holdout test.</p></div></Card></div>
    </div>{error && <div className="inline-error">Some model panels could not be loaded: {error}</div>}
  </div>;
}
